CREATE TABLE [dbo].[META_CONFIGURATION_CORE] (
    [META_CONFIGURATION_CORE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [SOURCE_ENTITY_ID]           INT           NOT NULL,
    [SOURCE_ENTITY_NAME]         VARCHAR (500) NULL,
    [CONFIGURATION_CATEGORY]     VARCHAR (200) NOT NULL,
    [CONFIGURATION_NAME]         VARCHAR (200) NOT NULL,
    [CONFIGURATION_VALUE]        VARCHAR (MAX) NULL,
    [IS_ACTIVEYN]                CHAR (1)      DEFAULT ('Y') NULL,
    [CREATED_BY]                 VARCHAR (100) NULL,
    [CREATED_DT]                 DATETIME2 (7) DEFAULT (getdate()) NULL,
    [LAST_UPDATED_BY]            VARCHAR (100) NULL,
    [LAST_UPDATED_DT]            DATETIME2 (7) NULL,
    CONSTRAINT [PK_META_CONFIGURATION_CORE] PRIMARY KEY CLUSTERED ([META_CONFIGURATION_CORE_ID] ASC),
    CONSTRAINT [FK_META_CONFIGURATION_CORE_SOURCE_ENTITY] FOREIGN KEY ([SOURCE_ENTITY_ID]) REFERENCES [dbo].[META_SOURCE_ENTITY] ([SOURCE_ENTITY_ID])
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UIDX_META_CONFIGURATION_CORE]
    ON [dbo].[META_CONFIGURATION_CORE]([SOURCE_ENTITY_ID] ASC, [CONFIGURATION_CATEGORY] ASC, [CONFIGURATION_NAME] ASC);


GO

