CREATE TABLE [dbo].[META_CONNECTION_PROPERTY] (
    [META_CONNECTION_PROPERTY_ID] INT            IDENTITY (1, 1) NOT NULL,
    [META_CONNECTION_ENDPOINT_ID] INT            NOT NULL,
    [PROPERTY_NAME]               VARCHAR (500)  NOT NULL,
    [PROPERTY_VALUE]              VARCHAR (4000) NULL,
    [CREATED_BY]                  VARCHAR (100)  NULL,
    [CREATED_DT]                  DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [LAST_UPDATED_BY]             VARCHAR (100)  NULL,
    [LAST_UPDATED_DT]             DATETIME2 (7)  NULL,
    [IS_ACTIVEYN]                 CHAR (1)       DEFAULT ('Y') NULL,
    CONSTRAINT [PK_META_CONNECTION_PROPERTY] PRIMARY KEY CLUSTERED ([META_CONNECTION_PROPERTY_ID] ASC),
    CONSTRAINT [FK_META_CONNECTION_PROPERTY_ENDPOINT] FOREIGN KEY ([META_CONNECTION_ENDPOINT_ID]) REFERENCES [dbo].[META_CONNECTION_ENDPOINT] ([META_CONNECTION_ENDPOINT_ID])
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UIDX_META_CONNECTION_PROPERTY]
    ON [dbo].[META_CONNECTION_PROPERTY]([META_CONNECTION_ENDPOINT_ID] ASC, [PROPERTY_NAME] ASC);


GO

