CREATE TABLE [dbo].[META_ORCHESTRATION] (
    [META_ORCHESTRATION_ID]       INT            IDENTITY (1, 1) NOT NULL,
    [TRIGGER_NAME]                VARCHAR (500)  NOT NULL,
    [SOURCE_ENTITY_ID]            INT            NOT NULL,
    [SOURCE_ENTITY_NAME]          VARCHAR (500)  NULL,
    [ORDER_OF_OPERATIONS]         INT            NULL,
    [META_CONNECTION_ENDPOINT_ID] INT            NOT NULL,
    [TARGET_ENTITY]               VARCHAR (4000) NULL,
    [PRIMARY_KEYS]                VARCHAR (4000) NULL,
    [PROCESSING_METHOD]           VARCHAR (200)  NULL,
    [IS_ACTIVEYN]                 CHAR (1)       DEFAULT ('Y') NULL,
    [CREATED_BY]                  VARCHAR (100)  NULL,
    [CREATED_DT]                  DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [LAST_UPDATED_BY]             VARCHAR (100)  NULL,
    [LAST_UPDATED_DT]             DATETIME2 (7)  NULL,
    [EXECUTION_ARTIFACT_TYPE]     VARCHAR (20)   DEFAULT ('FRAMEWORK') NOT NULL,
    [EXECUTION_WORKSPACE_ID]      VARCHAR (100)  NULL,
    [EXECUTION_ARTIFACT_ID]       VARCHAR (1000) NULL,
    [EXECUTION_ARTIFACT_PARAMS]   VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_META_ORCHESTRATION] PRIMARY KEY CLUSTERED ([META_ORCHESTRATION_ID] ASC),
    CONSTRAINT [CHK_META_ORCHESTRATION_ARTIFACT_ID] CHECK ([EXECUTION_ARTIFACT_TYPE]='FRAMEWORK' OR [EXECUTION_ARTIFACT_ID] IS NOT NULL),
    CONSTRAINT [CHK_META_ORCHESTRATION_ARTIFACT_TYPE] CHECK ([EXECUTION_ARTIFACT_TYPE]='DATAFLOW_GEN2' OR [EXECUTION_ARTIFACT_TYPE]='PIPELINE' OR [EXECUTION_ARTIFACT_TYPE]='NOTEBOOK' OR [EXECUTION_ARTIFACT_TYPE]='STORED_PROCEDURE' OR [EXECUTION_ARTIFACT_TYPE]='FRAMEWORK'),
    CONSTRAINT [FK_META_ORCHESTRATION] FOREIGN KEY ([META_CONNECTION_ENDPOINT_ID]) REFERENCES [dbo].[META_CONNECTION_ENDPOINT] ([META_CONNECTION_ENDPOINT_ID]),
    CONSTRAINT [FK_META_ORCHESTRATION_SOURCE_ENTITY] FOREIGN KEY ([SOURCE_ENTITY_ID]) REFERENCES [dbo].[META_SOURCE_ENTITY] ([SOURCE_ENTITY_ID])
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UIDX_META_ORCHESTRATION]
    ON [dbo].[META_ORCHESTRATION]([TRIGGER_NAME] ASC, [SOURCE_ENTITY_ID] ASC);


GO

