CREATE TABLE [dbo].[META_CONFIGURATION_ADVANCED] (
    [META_CONFIGURATION_ADVANCED_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [SOURCE_ENTITY_ID]                   INT           NOT NULL,
    [SOURCE_ENTITY_NAME]                 VARCHAR (500) NULL,
    [CONFIGURATION_CATEGORY]             VARCHAR (200) NOT NULL,
    [CONFIGURATION_NAME]                 VARCHAR (200) NOT NULL,
    [CONFIGURATION_NAME_INSTANCE_NUMBER] INT           NOT NULL,
    [CONFIGURATION_ATTRIBUTE_NAME]       VARCHAR (200) NOT NULL,
    [CONFIGURATION_ATTRIBUTE_VALUE]      VARCHAR (MAX) NULL,
    [IS_ACTIVEYN]                        CHAR (1)      DEFAULT ('Y') NULL,
    [CREATED_BY]                         VARCHAR (100) NULL,
    [CREATED_DT]                         DATETIME2 (7) DEFAULT (getdate()) NULL,
    [LAST_UPDATED_BY]                    VARCHAR (100) NULL,
    [LAST_UPDATED_DT]                    DATETIME2 (7) NULL,
    CONSTRAINT [PK_META_CONFIGURATION_ADVANCED] PRIMARY KEY CLUSTERED ([META_CONFIGURATION_ADVANCED_ID] ASC),
    CONSTRAINT [FK_META_CONFIGURATION_ADVANCED_SOURCE_ENTITY] FOREIGN KEY ([SOURCE_ENTITY_ID]) REFERENCES [dbo].[META_SOURCE_ENTITY] ([SOURCE_ENTITY_ID])
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UIDX_META_CONFIGURATION_ADVANCED]
    ON [dbo].[META_CONFIGURATION_ADVANCED]([SOURCE_ENTITY_ID] ASC, [CONFIGURATION_CATEGORY] ASC, [CONFIGURATION_NAME] ASC, [CONFIGURATION_NAME_INSTANCE_NUMBER] ASC, [CONFIGURATION_ATTRIBUTE_NAME] ASC);


GO

