CREATE TABLE [dbo].[META_INGESTION_LOG] (
    [META_INGESTION_LOG_ID]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [META_ORCHESTRATION_ID]        INT            NOT NULL,
    [SOURCE_ENTITY_ID]             INT            NOT NULL,
    [SOURCE_ENTITY_NAME]           VARCHAR (500)  NULL,
    [DATA_ENDPOINT_NAME]           VARCHAR (500)  NOT NULL,
    [TARGET_ENTITY]                VARCHAR (4000) NULL,
    [PROCESSING_METHOD]            VARCHAR (200)  NULL,
    [TRIGGER_NAME]                 VARCHAR (500)  NULL,
    [TRIGGER_EXECUTION_ID]         VARCHAR (500)  NULL,
    [TRIGGER_EXECUTION_START_TIME] DATETIME2 (6)  NULL,
    [RUN_START_DT]                 DATETIME2 (6)  NULL,
    [RUN_END_DT]                   DATETIME2 (6)  NULL,
    [RUN_STATUS]                   VARCHAR (20)   NOT NULL,
    [WATERMARK_VALUE_USED]         VARCHAR (4000) NULL,
    [WATERMARK_VALUE_NEW]          VARCHAR (4000) NULL,
    [ROWS_READ]                    BIGINT         NULL,
    [ROWS_WRITTEN]                 BIGINT         NULL,
    [ROWS_REJECTED]                BIGINT         NULL,
    [ERROR_MESSAGE]                VARCHAR (MAX)  NULL,
    [FABRIC_MONITOR_URL]           VARCHAR (4000) NULL,
    [EXECUTION_ARTIFACT_TYPE]      VARCHAR (20)   NULL,
    [EXECUTION_ARTIFACT_ID]        VARCHAR (1000) NULL,
    [ARTIFACT_RUN_ID]              VARCHAR (500)  NULL,
    [CREATED_DT]                   DATETIME2 (6)  DEFAULT (sysutcdatetime()) NOT NULL,
    [DATE_KEY]                     INT            NULL,
    CONSTRAINT [PK_META_INGESTION_LOG] PRIMARY KEY CLUSTERED ([META_INGESTION_LOG_ID] ASC),
    CONSTRAINT [CHK_META_INGESTION_LOG_ARTIFACT_TYPE] CHECK ([EXECUTION_ARTIFACT_TYPE] IS NULL OR ([EXECUTION_ARTIFACT_TYPE]='DATAFLOW_GEN2' OR [EXECUTION_ARTIFACT_TYPE]='PIPELINE' OR [EXECUTION_ARTIFACT_TYPE]='NOTEBOOK' OR [EXECUTION_ARTIFACT_TYPE]='STORED_PROCEDURE' OR [EXECUTION_ARTIFACT_TYPE]='FRAMEWORK'))
);


GO

CREATE NONCLUSTERED INDEX [NCI_META_INGESTION_LOG_ARTIFACT]
    ON [dbo].[META_INGESTION_LOG]([EXECUTION_ARTIFACT_TYPE] ASC, [RUN_STATUS] ASC);


GO

CREATE NONCLUSTERED INDEX [NCI_META_INGESTION_LOG_DATE]
    ON [dbo].[META_INGESTION_LOG]([DATE_KEY] ASC);


GO

CREATE NONCLUSTERED INDEX [NCI_META_INGESTION_LOG_EXEC]
    ON [dbo].[META_INGESTION_LOG]([TRIGGER_EXECUTION_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [NCI_META_INGESTION_LOG_ORCH]
    ON [dbo].[META_INGESTION_LOG]([META_ORCHESTRATION_ID] ASC, [RUN_START_DT] DESC);


GO

