CREATE TABLE [dbo].[META_CONNECTION_ENDPOINT] (
    [META_CONNECTION_ENDPOINT_ID] INT            IDENTITY (1, 1) NOT NULL,
    [DATA_ENDPOINT_NAME]          VARCHAR (500)  NOT NULL,
    [DATA_ENDPOINT_TYPE]          VARCHAR (50)   NOT NULL,
    [DATA_ENDPOINT_TECH_TYPE]     VARCHAR (100)  NOT NULL,
    [AUTH_TYPE]                   VARCHAR (30)   NULL,
    [GATEWAY_REQUIRED_YN]         CHAR (1)       DEFAULT ('N') NULL,
    [DESCRIPTION]                 VARCHAR (1000) NULL,
    [IS_ACTIVEYN]                 CHAR (1)       DEFAULT ('Y') NULL,
    [CREATED_BY]                  VARCHAR (100)  NULL,
    [CREATED_DT]                  DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [LAST_UPDATED_BY]             VARCHAR (100)  NULL,
    [LAST_UPDATED_DT]             DATETIME2 (7)  NULL,
    CONSTRAINT [PK_META_CONNECTION_ENDPOINT] PRIMARY KEY CLUSTERED ([META_CONNECTION_ENDPOINT_ID] ASC),
    CONSTRAINT [CHK_META_CONNECTION_ENDPOINT_AUTH_TYPE] CHECK ([AUTH_TYPE] IS NULL OR ([AUTH_TYPE]='GATEWAY_SQL_AUTH' OR [AUTH_TYPE]='KEY_VAULT_SECRET' OR [AUTH_TYPE]='SERVICE_PRINCIPAL' OR [AUTH_TYPE]='ENTRA_MANAGED_IDENTITY')),
    CONSTRAINT [CHK_META_CONNECTION_ENDPOINT_TYPE] CHECK ([DATA_ENDPOINT_TYPE]='TARGET' OR [DATA_ENDPOINT_TYPE]='SOURCE')
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UIDX_META_CONNECTION_ENDPOINT_NAME]
    ON [dbo].[META_CONNECTION_ENDPOINT]([DATA_ENDPOINT_NAME] ASC);


GO

