CREATE TABLE [dbo].[META_SOURCE_ENTITY] (
    [SOURCE_ENTITY_ID]              INT            IDENTITY (1, 1) NOT NULL,
    [SOURCE_ENTITY_NAME]            VARCHAR (500)  NOT NULL,
    [SOURCE_CONNECTION_ENDPOINT_ID] INT            NOT NULL,
    [DESCRIPTION]                   VARCHAR (1000) NULL,
    [IS_ACTIVEYN]                   CHAR (1)       DEFAULT ('Y') NULL,
    [CREATED_BY]                    VARCHAR (100)  NULL,
    [CREATED_DT]                    DATETIME2 (7)  DEFAULT (getdate()) NULL,
    [LAST_UPDATED_BY]               VARCHAR (100)  NULL,
    [LAST_UPDATED_DT]               DATETIME2 (7)  NULL,
    CONSTRAINT [PK_META_SOURCE_ENTITY] PRIMARY KEY CLUSTERED ([SOURCE_ENTITY_ID] ASC),
    CONSTRAINT [FK_META_SOURCE_ENTITY_ENDPOINT] FOREIGN KEY ([SOURCE_CONNECTION_ENDPOINT_ID]) REFERENCES [dbo].[META_CONNECTION_ENDPOINT] ([META_CONNECTION_ENDPOINT_ID])
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UIDX_META_SOURCE_ENTITY_NAME]
    ON [dbo].[META_SOURCE_ENTITY]([SOURCE_ENTITY_NAME] ASC);


GO

